### ISSUE TITLE
Cannot hit docker container using end point 

### ISSUE THREAD

**Issue by Snedden** [aws-samples/aws-sam-java-rest#6]
Hello I am having trouble following the documentation on the readMe file, below are the steps I follow

### Steps to reproduce:

- Get dependencies

:
`mvn package`

- Run docker container : 

`docker run -p 8000:8000 amazon/dynamodb-local`
Output:
```
Initializing DynamoDB Local with the following configuration:
Port:   8000
InMemory:       true
DbPath: null
SharedDb:       false
shouldDelayTransientStatuses:   false
CorsParams:  
``` 

- Checking...

 `docker ps`

```
CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS              PORTS                    NAMES
340025693b3a        amazon/dynamodb-local   "java -jar DynamoDBL…"   About a minute ago   Up About a minute   0.0.0.0:8000->8000/tcp   modest_mahavira
```

- Start api:

`sam local start-api --env-vars src/test/resources/test_environment_windows.json`

Output:
```
2019-06-07 06:01:01 Found credentials in shared credentials file: ~/.aws/credentials
2019-06-07 06:01:01 Mounting GetOrderFunction at http://127.0.0.1:3000/orders/{order_id} [GET]
2019-06-07 06:01:01 Mounting CreateOrdersTableFunction at http://127.0.0.1:3000/_create_orders_table [POST]
2019-06-07 06:01:01 Mounting GetOrdersFunction at http://127.0.0.1:3000/orders [GET]
2019-06-07 06:01:01 Mounting DeleteOrderFunction at http://127.0.0.1:3000/orders/{order_id} [DELETE]
2019-06-07 06:01:01 Mounting CreateOrderFunction at http://127.0.0.1:3000/orders [POST]
2019-06-07 06:01:01 Mounting UpdateOrderFunction at http://127.0.0.1:3000/orders/{order_id} [POST]
2019-06-07 06:01:01 You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatical
ly. You only need to restart SAM CLI if you update your AWS SAM template
2019-06-07 06:01:01  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
```

- Try hitting http://localhost:3000/orders,

**Errors  out saying :**
`software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: docker.for.windows.localhost`

Expected result: 

To work as documented

- My system info:

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-FC3Q9EQ
System Manufacturer	Dell Inc.
System Model	Inspiron 15 7000 Gaming
System Type	x64-based PC
System SKU	0798
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.9.0, 1/10/2019
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17134.765"
User Name	DESKTOP-FC3Q9EQ\sgg35
Time Zone	Eastern Daylight Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	5.81 GB
Total Virtual Memory	18.2 GB
Available Virtual Memory	2.98 GB
Page File Space	2.38 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
```

- Docker version:

`Docker version 18.09.2, build 6247962`

- sam cli:

`SAM CLI, version 0.16.0`

- Complete stack trace:

```
Fetching lambci/lambda:java8 Docker container image......
2019-06-07 06:07:26 Mounting D:\Temp\tmpea9_931o as /var/task:ro,delegated inside runtime container
Jun 07, 2019 10:07:28 AM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
?[32mSTART RequestId: 6744a18e-e17b-4c0a-a0d1-d815149dc554 Version: $LATEST?[0m
?[31msoftware.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: docker.for.windows.localhost
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:93)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.handleThrownException(RetryableStage.java:170)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:123)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:69)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:49)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:42)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:25)
        at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:283)
        at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:91)
        at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:103)
        at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:68)
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
        at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.scan(DefaultDynamoDbClient.java:2456)
        at com.amazonaws.dao.OrderDao.getOrders(OrderDao.java:152)
        at com.amazonaws.handler.GetOrdersHandler.handleRequest(GetOrdersHandler.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.net.UnknownHostException: docker.for.windows.localhost
        at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at software.amazon.awssdk.http.apache.internal.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:80)
        at com.sun.proxy.$Proxy0.connect(Unknown Source)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at software.amazon.awssdk.http.apache.internal.impl.ApacheSdkHttpClient.execute(ApacheSdkHttpClient.java:72)
        at software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:200)
        at software.amazon.awssdk.http.apache.ApacheHttpClient.access$400(ApacheHttpClient.java:92)
        at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:178)
        at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:175)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:58)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:50)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:34)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:145)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:111)
        ... 22 more
?[0m
?[32mEND RequestId: 6744a18e-e17b-4c0a-a0d1-d815149dc554?[0m
?[32mREPORT RequestId: 6744a18e-e17b-4c0a-a0d1-d815149dc554     Duration: 6583.42 ms    Billed Duration: 6600 ms        Memory Size: 128 MB     Max Memory Used: 8 MB   ?[0m
2019-06-07 06:07:41 Invalid API Gateway Response Keys: {'stackTrace', 'errorType', 'errorMessage', 'cause'} in {'errorMessage': 'Unable to execute HTTP request: docker.for.windows.localhost', 'errorType': 'soft
ware.amazon.awssdk.core.exception.SdkClientException', 'stackTrace': ['software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:93)', 'software.amazon.awssdk.core.inter
nal.http.pipeline.stages.RetryableStage$RetryExecutor.handleThrownException(RetryableStage.java:170)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableSt
age.java:123)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:69)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(Retr
yableStage.java:49)', 'software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)', 'software.amazon.awssdk.core.internal.ht
tp.StreamManagingStage.execute(StreamManagingStage.java:57)', 'software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:42)', 'software.amazon.awssdk.core.internal.http.pip
eline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)', 'software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.exe
cute(RequestPipelineBuilder.java:205)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)', 'software.am
azon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:25)', 'software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$
RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:283)', 'software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:91)', 'software.amazon.awssdk.core.client
.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:103)', 'software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:68)', 'software.amazon.awssdk.core.c
lient.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)', 'software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)', 'software.amazon.awssdk.ser
vices.dynamodb.DefaultDynamoDbClient.scan(DefaultDynamoDbClient.java:2456)', 'com.amazonaws.dao.OrderDao.getOrders(OrderDao.java:152)', 'com.amazonaws.handler.GetOrdersHandler.handleRequest(GetOrdersHandler.jav
a:64)', 'sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)', 'sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)', 'sun.reflect.DelegatingMethodAccessorImpl.invoke(Delegatin
gMethodAccessorImpl.java:43)', 'java.lang.reflect.Method.invoke(Method.java:498)'], 'cause': {'errorMessage': 'docker.for.windows.localhost', 'errorType': 'java.net.UnknownHostException', 'stackTrace': ['java.n
et.InetAddress.getAllByName0(InetAddress.java:1281)', 'java.net.InetAddress.getAllByName(InetAddress.java:1193)', 'java.net.InetAddress.getAllByName(InetAddress.java:1127)', 'org.apache.http.impl.conn.SystemDef
aultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)', 'org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)', 'org.apache.http.impl.conn.Pool
ingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)', 'sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)', 'sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcce
ssorImpl.java:62)', 'sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)', 'java.lang.reflect.Method.invoke(Method.java:498)', 'software.amazon.awssdk.http.apache.internal.conn
.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:80)', 'com.sun.proxy.$Proxy0.connect(Unknown Source)', 'org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClient
Exec.java:381)', 'org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)', 'org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)', 'org.apache.http.impl.client.Inte
rnalHttpClient.doExecute(InternalHttpClient.java:185)', 'org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)', 'org.apache.http.impl.client.CloseableHttpClient.execute(Closeable
HttpClient.java:56)', 'software.amazon.awssdk.http.apache.internal.impl.ApacheSdkHttpClient.execute(ApacheSdkHttpClient.java:72)', 'software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.j
ava:200)', 'software.amazon.awssdk.http.apache.ApacheHttpClient.access$400(ApacheHttpClient.java:92)', 'software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:178)', 'software.amazon.a
wssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:175)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:58)', 'softwar
e.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:50)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRe
questStage.java:34)', 'software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)', 'software.amazon.awssdk.core.internal.ht
tp.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)', 'software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineSta
ge.execute(RequestPipelineBuilder.java:205)', 'software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)', 'software.amazon
.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$Retr
yExecutor.doExecute(RetryableStage.java:145)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:111)', 'software.amazon.awssdk.core.internal.ht
tp.pipeline.stages.RetryableStage.execute(RetryableStage.java:69)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:49)', 'software.amazon.awssdk.core.inter
nal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)', 'software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:
57)', 'software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:42)', 'software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineSta
ge.execute(RequestPipelineBuilder.java:205)', 'software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)', 'software.amazon
.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)', 'software.amazon.awssdk.core.internal.http.pipeline.stages.Execution
FailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:25)', 'software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient
.java:283)', 'software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:91)', 'software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHan
dler.java:103)', 'software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:68)', 'software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClient
Handler.java:44)', 'software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)', 'software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.scan(DefaultDynamoD
bClient.java:2456)', 'com.amazonaws.dao.OrderDao.getOrders(OrderDao.java:152)', 'com.amazonaws.handler.GetOrdersHandler.handleRequest(GetOrdersHandler.java:64)', 'sun.reflect.NativeMethodAccessorImpl.invoke0(Na
tive Method)', 'sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)', 'sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)', 'java.lang.reflect.Method
.invoke(Method.java:498)']}}
2019-06-07 06:07:41 Function returned an invalid response (must include one of: body, headers or statusCode in the response object). Response received: {"errorMessage":"Unable to execute HTTP request: docker.fo
r.windows.localhost","errorType":"software.amazon.awssdk.core.exception.SdkClientException","stackTrace":["software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:93)"
,"software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.handleThrownException(RetryableStage.java:170)","software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage
$RetryExecutor.execute(RetryableStage.java:123)","software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:69)","software.amazon.awssdk.core.internal.http.pipeline.st
ages.RetryableStage.execute(RetryableStage.java:49)","software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)","software.
amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)","software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:42)","software.amazon.a
wssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)","software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$Compos
ingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)","software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingSta
ge.java:37)","software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:25)","software.amazon.awssdk.core.internal.ht
tp.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:283)","software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:91)","software.ama
zon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:103)","software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:68)","software.
amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)","software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)","software
.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.scan(DefaultDynamoDbClient.java:2456)","com.amazonaws.dao.OrderDao.getOrders(OrderDao.java:152)","com.amazonaws.handler.GetOrdersHandler.handleRequest(GetO
rdersHandler.java:64)","sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)","sun.reflect.DelegatingMethodAccessorImpl.inv
oke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)"],"cause":{"errorMessage":"docker.for.windows.localhost","errorType":"java.net.UnknownHostException","stackTrace":["j
ava.net.InetAddress.getAllByName0(InetAddress.java:1281)","java.net.InetAddress.getAllByName(InetAddress.java:1193)","java.net.InetAddress.getAllByName(InetAddress.java:1127)","org.apache.http.impl.conn.SystemD
efaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)","org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)","org.apache.http.impl.conn.Pool
ingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)","sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccess
orImpl.java:62)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","software.amazon.awssdk.http.apache.internal.conn.Clie
ntConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:80)","com.sun.proxy.$Proxy0.connect(Unknown Source)","org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.ja
va:381)","org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)","org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)","org.apache.http.impl.client.InternalHttpCl
ient.doExecute(InternalHttpClient.java:185)","org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)","org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.j
ava:56)","software.amazon.awssdk.http.apache.internal.impl.ApacheSdkHttpClient.execute(ApacheSdkHttpClient.java:72)","software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:200)","sof
tware.amazon.awssdk.http.apache.ApacheHttpClient.access$400(ApacheHttpClient.java:92)","software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:178)","software.amazon.awssdk.http.apache
.ApacheHttpClient$1.call(ApacheHttpClient.java:175)","software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:58)","software.amazon.awssdk.cor
e.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:50)","software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:34)"
,"software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)","software.amazon.awssdk.core.internal.http.pipeline.RequestPip
elineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)","software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipel
ineBuilder.java:205)","software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)","software.amazon.awssdk.core.internal.htt
p.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)","software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(Retrya
bleStage.java:145)","software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:111)","software.amazon.awssdk.core.internal.http.pipeline.stages.Retryable
Stage.execute(RetryableStage.java:69)","software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:49)","software.amazon.awssdk.core.internal.http.pipeline.RequestPipel
ineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)","software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)","software.amazon.awssdk.co
re.internal.http.StreamManagingStage.execute(StreamManagingStage.java:42)","software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder
.java:205)","software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)","software.amazon.awssdk.core.internal.http.pipeline
.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)","software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execu
te(ExecutionFailureExceptionReportingStage.java:25)","software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:283)","software.amazon.awssdk.c
ore.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:91)","software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:103)","software.amazon.awssdk
.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:68)","software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)","software.amazon.awssdk
.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)","software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.scan(DefaultDynamoDbClient.java:2456)","com.amazonaws.dao.Orde
rDao.getOrders(OrderDao.java:152)","com.amazonaws.handler.GetOrdersHandler.handleRequest(GetOrdersHandler.java:64)","sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","sun.reflect.NativeMethodAccesso
rImpl.invoke(NativeMethodAccessorImpl.java:62)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)"]}}
2019-06-07 06:07:41 127.0.0.1 - - [07/Jun/2019 06:07:41] "GET /orders HTTP/1.1" 502 -
2019-06-07 06:07:42 127.0.0.1 - - [07/Jun/2019 06:07:42] "GET /favicon.ico HTTP/1.1" 403 -
```

- PS:

I tried running other containers in docker and exposing ports which work perfectly example

`docker run -d -p 80:80 nginx

`
So I don't think it something in docker that's missing here

**Comment by prakharvk** [comment]
I am facing the same issue, Did you get any solution to this ?

**Comment by synchrophoto** [comment]
> I am facing the same issue, Did you get any solution to this ?

It looks to me like there are 2 docker containers and the one is trying to connect to the DynamoDB local container. When that happens, docker networking needs to be set up and both containers on the same docker network. If you use compose, it solves this easier, but I am just guessing as to what the problem is based on what I am reading.
